version: "3.7"

services:
  pipecaller:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pipe-caller
    volumes:
      - /opt/workspace/pipes:/opt/workspace/pipes
    ports:
      - 9090:9090
